version: "3"

services:
  # Application

  main_database:
    image: "bitnami/postgresql"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_PASSWORD=secret
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_DATABASE=next_vaccination
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    deploy:
      resources:
        limits:
          memory: 2048M
          cpus: "1.0"

  # Kafka & Zookeeper

  zookeeper:
    image: "bitnami/zookeeper:3"
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-net
    deploy:
      resources:
        limits:
          memory: 1512M
          cpus: "0.5"

  kafka:
    image: "bitnami/kafka:2"
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - app-net
    deploy:
      resources:
        limits:
          memory: 1512M
          cpus: "0.5"

networks:
  app-net:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
  mongodb_data:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
